name: Question
description: Questions about Pip-rating, doubts and other issues.
body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the question in detail.
      placeholder: I have searched the Pip-rating documentation on a topic and I have not found any help about...
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have read the documentation and I have not found it.
          required: true
        - label: This is a question or something else. This is not a bug report, a feature request or a documentation issue.
          required: true
        - label: I have searched for this issue before posting it and there isn't a duplicate.
          required: true
